server:
  port: 8888
spring:
  application:
    name: olx-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gopalsingh462/olx-config
          username: gopalsingh462
          password: g9602105362
          clone-on-start: true